import {
  ALL_PLANS,
  B2C_PLANS,
  INSTITUTIONAL_ONLY,
  PLANS_WITH_PLANNING,
  isB2CPlan,
  SUBSCRIPTION_PRICE_CLP,
  MONTHLY_CREDITS,
  SIGNUP_CREDITS,
  CREDIT_PACK_SIZE,
  CREDIT_PACK_PRICE_CLP,
} from 'src/helpers/plans';

export default class PlansService {
  static ALL_PLANS = ALL_PLANS;
  static B2C_PLANS = B2C_PLANS;
  static INSTITUTIONAL_ONLY = INSTITUTIONAL_ONLY;
  static PLANS_WITH_PLANNING = PLANS_WITH_PLANNING;

  static SUBSCRIPTION_PRICE_CLP = SUBSCRIPTION_PRICE_CLP;
  static MONTHLY_CREDITS = MONTHLY_CREDITS;
  static SIGNUP_CREDITS = SIGNUP_CREDITS;
  static CREDIT_PACK_SIZE = CREDIT_PACK_SIZE;
  static CREDIT_PACK_PRICE_CLP = CREDIT_PACK_PRICE_CLP;

  static isB2CPlan(plan) {
    return isB2CPlan(plan);
  }
}
