// Bases Curriculares de la Educación Parvularia (Mineduc, 2018).
// Fuente: curriculumnacional.mineduc.cl — revisar con equipo pedagógico antes de publicar.
export const BCEP_VERSION = 'BCEP 2018';

export const TRAMOS = ['salaCuna', 'nivelMedio', 'transicion'];

export const AMBITOS = [
  {
    id: 'desarrollo-personal-social',
    name: 'Desarrollo Personal y Social',
    nucleos: [
      {
        id: 'identidad-autonomia',
        name: 'Identidad y autonomía',
        type: 'transversal',
        oas: {
          salaCuna: [
            { code: 'OA 1', text: 'Expresar vocal, gestual o corporalmente distintas necesidades o emociones (alegría, miedo, pena, entre otras).' },
            { code: 'OA 2', text: 'Manifestar satisfacción cuando percibe que adultos significativos le expresan afecto.' },
            { code: 'OA 3', text: 'Reconocer algunas emociones en adultos significativos, reaccionando frente a ellas.' },
            { code: 'OA 4', text: 'Manifestar sus preferencias por algunas situaciones, objetos y juegos.' },
            { code: 'OA 5', text: 'Manifestar interés por nuevas situaciones u objetos, ampliando su campo y repertorio de acción habitual.' },
            { code: 'OA 6', text: 'Reconocer algunos rasgos distintivos de su identidad, tales como: su nombre y su imagen física en el espejo.' },
            { code: 'OA 7', text: 'Incorporar rutinas básicas vinculadas a la alimentación, vigilia, sueño, higiene, y vestuario dentro de un contexto diferente a su hogar y sensible a sus necesidades personales.' },
          ],
          nivelMedio: [
            { code: 'OA 1', text: 'Representar verbal y corporalmente diferentes emociones y sentimientos, en sus juegos.' },
            { code: 'OA 2', text: 'Manifestar disposición y confianza al separarse de los adultos significativos.' },
            { code: 'OA 3', text: 'Reconocer en sí mismo, en otras personas y en personajes de cuentos, emociones tales como: tristeza, miedo, alegría, pena y rabia.' },
            { code: 'OA 4', text: 'Manifestar disposición para regular sus emociones y sentimientos, en función de las necesidades propias, de los demás y de algunos acuerdos para el funcionamiento grupal.' },
            { code: 'OA 5', text: 'Manifestar sus preferencias cuando participa o cuando solicita participar, en diversas situaciones cotidianas y juegos.' },
            { code: 'OA 6', text: 'Actuar con progresiva independencia, ampliando su repertorio de acciones, acorde a sus necesidades e intereses.' },
            { code: 'OA 7', text: 'Comunicar algunos rasgos de su identidad, como su nombre, sus características corporales, género y otros.' },
            { code: 'OA 8', text: 'Apreciar sus características identitarias, fortalezas y habilidades.' },
            { code: 'OA 9', text: 'Manifestar progresiva independencia en sus prácticas de alimentación, vigilia y sueño, vestimenta, higiene corporal, bucal y evacuación.' },
            { code: 'OA 10', text: 'Manifestar satisfacción y confianza por su autovalía, comunicando algunos desafíos alcanzados, tales como: saltar, hacer torres, sacar cáscara de huevos, entre otros.' },
            { code: 'OA 11', text: 'Identificar alimentos que se consumen en algunas celebraciones propias de su familia y comunidad.' },
            { code: 'OA 12', text: 'Representar sus pensamientos y experiencias, atribuyendo significados a objetos o elementos de su entorno, usando la imaginación en situaciones de juego.' },
          ],
          transicion: [
            { code: 'OA 1', text: 'Comunicar a los demás, emociones y sentimientos tales como: amor, miedo, alegría, ira, que le provocan diversas narraciones o situaciones observadas en forma directa o a través de TICs.' },
            { code: 'OA 2', text: 'Manifestar disposición y confianza para relacionarse con algunos adultos y pares que no son parte del grupo o curso.' },
            { code: 'OA 3', text: 'Reconocer emociones y sentimientos en otras personas, observadas en forma directa o a través de TICs.' },
            { code: 'OA 4', text: 'Expresar sus emociones y sentimientos autorregulándose en función de las necesidades propias, de los demás y las normas de funcionamiento grupal.' },
            { code: 'OA 5', text: 'Comunicar sus preferencias, opiniones, ideas, en diversas situaciones cotidianas y juegos.' },
            { code: 'OA 6', text: 'Planificar proyectos y juegos, en función de sus ideas e intereses, proponiendo actividades, organizando los recursos, incorporando los ajustes necesarios e iniciándose en la apreciación de sus resultados.' },
            { code: 'OA 7', text: 'Comunicar rasgos de su identidad de género, roles (nieta/o, vecino/a, entre otros), sentido de pertenencia y cualidades personales.' },
            { code: 'OA 8', text: 'Comunicar sus características identitarias, fortalezas, habilidades y desafíos personales.' },
            { code: 'OA 9', text: 'Cuidar su bienestar personal, llevando a cabo sus prácticas de higiene, alimentación y vestuario, con independencia y progresiva responsabilidad.' },
            { code: 'OA 10', text: 'Comunicar a otras personas desafíos alcanzados, identificando acciones que aportaron a su logro y definiendo nuevas metas.' },
            { code: 'OA 11', text: 'Distinguir parámetros establecidos para la regulación de alimentos, tales como: etiquetado de sellos, fechas de vencimiento, entre otros.' },
            { code: 'OA 12', text: 'Anticipar acciones y prever algunas situaciones o desafíos que se pueden presentar, en juegos, proyectos, sucesos que experimenta o que observa a través de TICs.' },
            { code: 'OA 13', text: 'Representar en juegos sociodramáticos, sus pensamientos y experiencias atribuyendo significados a objetos, personas y situaciones.' },
          ],
        },
      },
      {
        id: 'convivencia-ciudadania',
        name: 'Convivencia y ciudadanía',
        type: 'transversal',
        oas: {
          salaCuna: [
            { code: 'OA 1', text: 'Interactuar con pares y adultos significativos (a través de gestos y vocalizaciones, entre otros), en diferentes situaciones y juegos.' },
            { code: 'OA 2', text: 'Disfrutar de la cercanía de niños, niñas y adultos en juegos y situaciones cotidianas.' },
            { code: 'OA 3', text: 'Manifestar interés por lo que le sucede a otros niños y niñas, a través de acciones tales como: abrazar a quien está llorando, hacer cariños, entre otros.' },
            { code: 'OA 4', text: 'Manifestar interés por participar en celebraciones de su entorno significativo.' },
            { code: 'OA 5', text: 'Practicar algunas normas de convivencia, tales como: sentarse en su silla para almorzar, saludar, despedirse, y colaborar en acciones cotidianas.' },
            { code: 'OA 6', text: 'Manifestar disposición para responder positivamente o cambiar su comportamiento, frente a requerimientos del adulto, asociados a su seguridad y bienestar.' },
          ],
          nivelMedio: [
            { code: 'OA 1', text: 'Participar en actividades y juegos grupales con sus pares, conversando, intercambiando pertenencias, cooperando.' },
            { code: 'OA 2', text: 'Disfrutar de instancias de interacción social con diversas personas de la comunidad.' },
            { code: 'OA 3', text: 'Colaborar en situaciones cotidianas y de juego, proponiendo acciones simples frente a necesidades que presentan sus pares.' },
            { code: 'OA 4', text: 'Colaborar en actividades, conmemoraciones o celebraciones culturales de su familia y comunidad.' },
            { code: 'OA 5', text: 'Iniciarse en la resolución pacífica de conflictos, dialogando respecto de la situación, escuchando, opinando y proponiendo acciones para resolver.' },
            { code: 'OA 6', text: 'Manifestar disposición para practicar acuerdos de convivencia básica que regulan situaciones cotidianas y juegos.' },
            { code: 'OA 7', text: 'Identificar objetos, comportamientos y situaciones de riesgo que pueden atentar contra su seguridad, bienestar y el de los demás.' },
            { code: 'OA 8', text: 'Reconocer acciones correctas e incorrectas para la convivencia armónica del grupo, que se presentan en diferentes situaciones cotidianas y juegos.' },
            { code: 'OA 9', text: 'Manifestar interés por algunos de sus derechos, tales como: ser escuchados, tener un nombre, jugar, entre otros.' },
            { code: 'OA 10', text: 'Manifestar interés para interactuar con niños y niñas, reconociendo la diversidad de sus características y formas de vida (costumbres, fisonomía, lingüística, entre otras).' },
          ],
          transicion: [
            { code: 'OA 1', text: 'Participar en actividades y juegos colaborativos, planificando, acordando estrategias para un propósito común y asumiendo progresivamente responsabilidades en ellos.' },
            { code: 'OA 2', text: 'Participar en actividades solidarias, que integran a las familias, la comunidad educativa y local.' },
            { code: 'OA 3', text: 'Manifestar empatía y solidaridad frente a situaciones que vivencian sus pares, o que observa en textos o TICs, practicando acciones de escucha, apoyo y colaboración.' },
            { code: 'OA 4', text: 'Apreciar el significado que tienen para las personas y las comunidades, diversas manifestaciones culturales que se desarrollan en su entorno.' },
            { code: 'OA 5', text: 'Aplicar estrategias pacíficas frente a la resolución de conflictos cotidianos con otros niños y niñas.' },
            { code: 'OA 6', text: 'Respetar normas y acuerdos creados colaborativamente con pares y adultos, para el bienestar del grupo.' },
            { code: 'OA 7', text: 'Identificar objetos, comportamientos y situaciones de riesgo que pueden atentar contra su bienestar y seguridad, o la de los demás, proponiendo alternativas para enfrentarlas.' },
            { code: 'OA 8', text: 'Comprender que algunas de sus acciones y decisiones respecto al desarrollo de juegos y proyectos colectivos, influyen en las de sus pares.' },
            { code: 'OA 9', text: 'Reconocer, y progresivamente hacer respetar el derecho a expresarse libremente, a ser escuchado y a que su opinión sea tomada en cuenta.' },
            { code: 'OA 10', text: 'Reconocer progresivamente requerimientos esenciales de las prácticas de convivencia democrática, tales como: escucha de opiniones divergentes, el respeto por los demás, de los turnos, de los acuerdos de las mayorías.' },
            { code: 'OA 11', text: 'Apreciar la diversidad de las personas y sus formas de vida, tales como: singularidades fisonómicas, lingüísticas, religiosas, de género, entre otras.' },
          ],
        },
      },
      {
        id: 'corporalidad-movimiento',
        name: 'Corporalidad y movimiento',
        type: 'transversal',
        oas: {
          salaCuna: [
            { code: 'OA 1', text: 'Manifestar su agrado, al sentirse cómodo, seguro y contenido corporalmente.' },
            { code: 'OA 2', text: 'Descubrir partes de su cuerpo y algunas de sus características físicas, a través de diversas experiencias sensoriomotrices.' },
            { code: 'OA 3', text: 'Manifestar interés y satisfacción al moverse libremente en situaciones cotidianas y lúdicas.' },
            { code: 'OA 4', text: 'Ampliar sus posibilidades de exploración sensoriomotriz, adquiriendo control de la prensión palmar voluntaria (toma objetos, se pasa objetos de una mano a otra, entre otros) y la postura sedente.' },
            { code: 'OA 5', text: 'Adquirir desplazamiento gradual en sus distintas formas (girar, reptar, ponerse de pie, caminar), para disfrutar la ampliación de sus posibilidades de movimiento, exploración y juego.' },
            { code: 'OA 6', text: 'Coordinar movimientos de manipulación ubicando objetos en relación a su propio cuerpo, tales como: acercar objetos pequeños utilizando índice y pulgar en oposición.' },
            { code: 'OA 7', text: 'Explorar la alternancia de posturas y movimientos en acciones tales como: trepar, lanzar objetos o hacer ronda, adquiriendo control gradual de su cuerpo al jugar.' },
          ],
          nivelMedio: [
            { code: 'OA 1', text: 'Reconocer situaciones en que se siente cómodo corporalmente, manifestando al adulto su bienestar y su interés por mantener estas condiciones.' },
            { code: 'OA 2', text: 'Reconocer las principales partes, características físicas de su cuerpo y sus funciones en situaciones cotidianas y de juego.' },
            { code: 'OA 3', text: 'Experimentar diversas posibilidades de acción con su cuerpo, en situaciones cotidianas y de juego, identificando progresivamente el vocabulario asociado.' },
            { code: 'OA 4', text: 'Reconocer el bienestar que le produce el movimiento libre en situaciones cotidianas y lúdicas, manifestando su interés por desarrollarlo en forma frecuente.' },
            { code: 'OA 5', text: 'Perfeccionar su coordinación visomotriz fina, a través del uso de diversos objetos, juguetes y utensilios.' },
            { code: 'OA 6', text: 'Adquirir control y equilibrio en movimientos, posturas y desplazamientos que realiza en diferentes direcciones y en variadas situaciones cotidianas y juegos, con y sin implementos.' },
            { code: 'OA 7', text: 'Resolver desafíos prácticos en situaciones cotidianas y juegos, incorporando mayor precisión y coordinación en la realización de posturas, movimientos y desplazamientos, tales como: esquivar obstáculos o mantener equilibrio al subir escalas.' },
            { code: 'OA 8', text: 'Utilizar categorías de ubicación espacial y temporal, tales como: adelante/atrás, arriba/ abajo, adentro/afuera, antes/ después, rápido/lento, en situaciones cotidianas y lúdicas.' },
          ],
          transicion: [
            { code: 'OA 1', text: 'Manifestar iniciativa para resguardar el autocuidado de su cuerpo y su confortabilidad, en función de su propio bienestar.' },
            { code: 'OA 2', text: 'Apreciar sus características corporales, manifestando interés y cuidado por su bienestar y apariencia personal.' },
            { code: 'OA 3', text: 'Tomar conciencia de su cuerpo, de algunas de sus características internas (tales como: ritmo cardíaco, de respiración), de su esquema y progresivamente de su tono corporal y lateralidad, por medio de juegos.' },
            { code: 'OA 4', text: 'Comunicar nuevas posibilidades de acción logradas a través de su cuerpo en situaciones cotidianas y de juego, empleando vocabulario preciso.' },
            { code: 'OA 5', text: 'Comunicar el bienestar que le produce el movimiento, al ejercitar y recrear su cuerpo en forma habitual, con y sin implementos u obstáculos.' },
            { code: 'OA 6', text: 'Coordinar con precisión y eficiencia sus habilidades psicomotrices finas en función de sus intereses de exploración y juego.' },
            { code: 'OA 7', text: 'Resolver desafíos prácticos manteniendo control, equilibrio y coordinación al combinar diversos movimientos, posturas y desplazamientos tales como: lanzar y recibir, desplazarse en planos inclinados, seguir ritmos, en una variedad de juegos.' },
            { code: 'OA 8', text: 'Coordinar sus habilidades psicomotoras practicando posturas y movimientos de fuerza, resistencia y tracción tales como: tirar la cuerda, transportar objetos, utilizar implementos, en situaciones cotidianas y de juego.' },
            { code: 'OA 9', text: 'Utilizar categorías de ubicación espacial y temporal, tales como: adelante/atrás/al lado/entre, día/noche, hoy/ mañana, antes/durante/después, en situaciones cotidianas y lúdicas.' },
          ],
        },
      },
    ],
  },
  {
    id: 'comunicacion-integral',
    name: 'Comunicación Integral',
    nucleos: [
      {
        id: 'lenguaje-verbal',
        name: 'Lenguaje verbal',
        type: 'specific',
        oas: {
          salaCuna: [
            { code: 'OA 1', text: 'Expresar oralmente sus emociones y necesidades, a través de balbuceos, vocalizaciones y diversos recursos gestuales.' },
            { code: 'OA 2', text: 'Expresar oralmente sus necesidades e intereses, mediante la combinación de palabras y gestos, el uso de palabra-frase y progresivamente el empleo de frases simples.' },
            { code: 'OA 3', text: 'Identificar progresivamente la intención comunicativa de las distintas personas de su entorno a partir de sus expresiones verbales, no verbales y paraverbales.' },
            { code: 'OA 4', text: 'Comprender mensajes simples y breves en juegos y situaciones comunicativas cotidianas, respondiendo en forma gestual y corporal.' },
            { code: 'OA 5', text: 'Reconocer sonidos de diferentes fuentes sonoras de su entorno cotidiano, tales como objetos, artefactos, instrumentos musicales, animales, naturaleza.' },
            { code: 'OA 6', text: 'Incorporar nuevas palabras a su repertorio lingüístico para comunicarse con otros, en juegos y conversaciones.' },
            { code: 'OA 7', text: 'Disfrutar de distintos textos gráficos (libros de cuentos, láminas, entre otros) al manipularlos y observar sus imágenes.' },
            { code: 'OA 8', text: 'Comprender progresivamente, a partir de la escucha atenta, algunos contenidos explícitos de textos literarios y no literarios, respondiendo preguntas simples, en forma oral o gestual (¿qué es?, ¿quién es?, ¿dónde está?).' },
          ],
          nivelMedio: [
            { code: 'OA 1', text: 'Expresarse oralmente, empleando estructuras oracionales simples y respetando patrones gramaticales básicos, en distintas situaciones cotidianas y juegos.' },
            { code: 'OA 2', text: 'Comprender mensajes simples como instrucciones explícitas, explicaciones y preguntas relativas a objetos, personas, acciones, tiempo y lugar, identificando la intencionalidad comunicativa de diversos interlocutores.' },
            { code: 'OA 3', text: 'Identificar algunos atributos de los sonidos de diferentes fuentes sonoras como intensidad (fuerte/suave), velocidad (rápido/lento).' },
            { code: 'OA 4', text: 'Incorporar progresivamente nuevas palabras, al comunicar oralmente temas variados de su interés e información básica, en distintas situaciones cotidianas.' },
            { code: 'OA 5', text: 'Manifestar interés por descubrir el contenido de textos de diferentes formatos, a través de la manipulación, la exploración, la escucha atenta y la formulación de preguntas.' },
            { code: 'OA 6', text: 'Comprender a partir de la escucha atenta, contenidos explícitos de textos literarios y no literarios, reconociendo ideas centrales, señalando preferencias, realizando sencillas descripciones, preguntando sobre el contenido.' },
            { code: 'OA 7', text: 'Reconocer progresivamente el significado de diversas imágenes, logos, símbolos de su entorno cotidiano, en diversos soportes (incluye uso de TICs).' },
            { code: 'OA 8', text: 'Producir sus propios signos gráficos en situaciones lúdicas.' },
          ],
          transicion: [
            { code: 'OA 1', text: 'Expresarse oralmente en forma clara y comprensible, empleando estructuras oracionales completas, conjugaciones verbales adecuadas y precisas con los tiempos, personas e intenciones comunicativas.' },
            { code: 'OA 2', text: 'Comprender textos orales como preguntas, explicaciones, relatos, instrucciones y algunos conceptos abstractos en distintas situaciones comunicativas, identificando la intencionalidad comunicativa de diversos interlocutores.' },
            { code: 'OA 3', text: 'Descubrir en contextos lúdicos, atributos fonológicos de palabras conocidas, tales como conteo de palabras, segmentación y conteo de sílabas, identificación de sonidos finales e iniciales.' },
            { code: 'OA 4', text: 'Comunicar oralmente temas de su interés, empleando un vocabulario variado e incorporando palabras nuevas y pertinentes a las distintas situaciones comunicativas e interlocutores.' },
            { code: 'OA 5', text: 'Manifestar interés por descubrir el contenido y algunos propósitos de diferentes textos escritos (manipulando, explorando, realizando descripciones y conjeturas) a través del contacto cotidiano con algunos de ellos, o del uso de TICs.' },
            { code: 'OA 6', text: 'Comprender contenidos explícitos de textos literarios y no literarios, a partir de la escucha atenta, describiendo información y realizando progresivamente inferencias y predicciones.' },
            { code: 'OA 7', text: 'Reconocer palabras que se encuentran en diversos soportes asociando algunos fonemas a sus correspondientes grafemas.' },
            { code: 'OA 8', text: 'Representar gráficamente algunos trazos, letras, signos, palabras significativas y mensajes simples legibles, utilizando diferentes recursos y soportes en situaciones auténticas.' },
            { code: 'OA 9', text: 'Comunicar mensajes simples en la lengua indígena pertinente a la comunidad donde habita.' },
            { code: 'OA 10', text: 'Reconocer algunas palabras o mensajes sencillos de lenguas maternas de sus pares, distintas al castellano.' },
          ],
        },
      },
      {
        id: 'lenguajes-artisticos',
        name: 'Lenguajes artísticos',
        type: 'specific',
        oas: {
          salaCuna: [
            { code: 'OA 1', text: 'Manifestar interés por los sonidos, las texturas, los colores y la luminosidad de su entorno, respondiendo a través de diversas formas, tales como balbuceo, gestos, sonrisas, entre otros.' },
            { code: 'OA 2', text: 'Producir sonidos con su voz, su cuerpo y diversos objetos sonoros, en forma espontánea o por imitación.' },
            { code: 'OA 3', text: 'Imitar gestos, movimientos, sonidos de su entorno significativo, a través de diversos medios.' },
            { code: 'OA 4', text: 'Manifestar sus preferencias por recursos expresivos presentes en piezas musicales, visuales, y escénicas, a través de gestos, movimientos, palabras, entre otros.' },
            { code: 'OA 5', text: 'Expresar corporalmente las emociones y sensaciones que le provocan algunas piezas musicales, bailando, cantando e intentando seguir el ritmo.' },
            { code: 'OA 6', text: 'Experimentar sus posibilidades de expresión plástica a través de diversos recursos, produciendo sus primeros garabateos espontáneos.' },
          ],
          nivelMedio: [
            { code: 'OA 1', text: 'Manifestar interés por diversas producciones artísticas (arquitectura, modelado, piezas musicales, pintura, dibujos, títeres, obras de teatro, danzas, entre otras), describiendo algunas características.' },
            { code: 'OA 2', text: 'Expresar sus preferencias, sensaciones y emociones relacionadas con diferentes recursos expresivos que se encuentran en sencillas obras visuales (colorido, formas), musicales (fuente, intensidad del sonido) o escénicas (desplazamiento, vestimenta, carácter expresivo).' },
            { code: 'OA 3', text: 'Interpretar canciones y juegos musicales, experimentando con diversos recursos tales como, la voz, el cuerpo, instrumentos musicales y objetos.' },
            { code: 'OA 4', text: 'Expresar corporalmente sensaciones y emociones experimentando con mímica, juegos teatrales, rondas, bailes y danzas.' },
            { code: 'OA 5', text: 'Expresar emociones, ideas y experiencias por medio de la plástica experimentando con recursos pictóricos, gráficos y de modelado.' },
            { code: 'OA 6', text: 'Experimentar diversas posibilidades de expresión, combinando lenguajes artísticos en sus producciones.' },
            { code: 'OA 7', text: 'Representar a través del dibujo, diversos elementos de su entorno, incorporando figuras cerradas, trazos intencionados y primeros esbozos de la figura humana.' },
          ],
          transicion: [
            { code: 'OA 1', text: 'Apreciar producciones artísticas de diversos contextos (en forma directa o a través de medios tecnológicos), describiendo y comparando algunas características visuales, musicales o escénicas (desplazamiento, ritmo, carácter expresivo, colorido, formas, diseño, entre otros).' },
            { code: 'OA 2', text: 'Comunicar sus impresiones, emociones e ideas respecto de diversas obras de arte, producciones propias y de sus pares (artesanías, piezas musicales, obras plásticas y escénicas, entre otras).' },
            { code: 'OA 3', text: 'Interpretar canciones y juegos musicales, utilizando de manera integrada diversos recursos tales como, la voz, el cuerpo, instrumentos musicales y objetos.' },
            { code: 'OA 4', text: 'Expresar corporalmente sensaciones, emociones e ideas a partir de la improvisación de escenas dramáticas, juegos teatrales, mímica y danza.' },
            { code: 'OA 5', text: 'Representar plásticamente emociones, ideas, experiencias e intereses, a través de líneas, formas, colores, texturas, con recursos y soportes en plano y volumen.' },
            { code: 'OA 6', text: 'Experimentar diversas combinaciones de expresión plástica, corporal y musical, comunicando las razones del proceso realizado.' },
            { code: 'OA 7', text: 'Representar a través del dibujo, sus ideas, intereses y experiencias, incorporando detalles a las figuras humanas y a objetos de su entorno, ubicándolos en parámetros básicos de organización espacial (arriba/abajo, dentro/fuera).' },
          ],
        },
      },
    ],
  },
  {
    id: 'interaccion-comprension-entorno',
    name: 'Interacción y Comprensión del Entorno',
    nucleos: [
      {
        id: 'exploracion-entorno-natural',
        name: 'Exploración del entorno natural',
        type: 'specific',
        oas: {
          salaCuna: [
            { code: 'OA 1', text: 'Manifestar curiosidad y asombro por algunos elementos, situaciones y fenómenos que ocurren en su entorno natural cercano, tales como: arena, lluvia, viento, entre otros.' },
            { code: 'OA 2', text: 'Reconocer algunos elementos representativos de su entorno natural, tales como: animales, plantas, ríos, cerros, desierto.' },
            { code: 'OA 3', text: 'Explorar su entorno, observando, manipulando y experimentando con diversos materiales de su interés, tales como: mezclar agua con tierra, recoger hojas o ramas, trasladar piedras, hacer huellas.' },
            { code: 'OA 4', text: 'Descubrir características de animales al observarlos en forma directa, en textos y en imágenes.' },
            { code: 'OA 5', text: 'Colaborar en actividades sencillas de cuidado de la naturaleza, tales como: regar, recoger hojas, trasladar ramitas, entre otras.' },
          ],
          nivelMedio: [
            { code: 'OA 1', text: 'Manifestar interés y asombro por diversos elementos, situaciones y fenómenos del entorno natural, explorando, observando, preguntando, describiendo, agrupando, entre otros.' },
            { code: 'OA 2', text: 'Comunicar verbalmente características de elementos y paisajes de su entorno natural, tales como cuerpos celestes, cerros, desierto, flora; y de fenómenos como marejadas, sismos, tormentas, sequías.' },
            { code: 'OA 3', text: 'Descubrir que el sol es fuente de luz y calor para el planeta, a través de experiencias directas o TICs.' },
            { code: 'OA 4', text: 'Comunicar algunas propiedades básicas de los elementos naturales que explora, tales como: colores, texturas, tamaños, temperaturas entre otras.' },
            { code: 'OA 5', text: 'Distinguir una variedad progresivamente más amplia de animales y plantas, respecto a sus características (tamaño, color, textura y morfología), sus necesidades básicas y los lugares que habitan, al observarlos en forma directa, en libros ilustrados o en TICs.' },
            { code: 'OA 6', text: 'Colaborar en situaciones cotidianas, en acciones que contribuyen al desarrollo de ambientes sostenibles, tales como cerrar las llaves de agua, apagar aparatos eléctricos, entre otras.' },
            { code: 'OA 7', text: 'Emplear instrumentos y herramientas de observación y recolección (lupas, frascos, recipientes, botellas, cucharas, embudos, pinzas, entre otros) en la exploración del entorno natural.' },
            { code: 'OA 8', text: 'Experimentar mezclas y disoluciones con materiales cotidianos tales como: burbujas de jabón, agua salada, gelatina, describiendo los cambios observados.' },
            { code: 'OA 9', text: 'Reconocer que el aire y el agua son elementos vitales para las personas, los animales y las plantas, y que estos elementos pueden encontrarse con o sin contaminación.' },
          ],
          transicion: [
            { code: 'OA 1', text: 'Manifestar interés y asombro al ampliar información sobre cambios que ocurren en el entorno natural, a las personas, animales, plantas, lugares y cuerpos celestes, utilizando diversas fuentes y procedimientos.' },
            { code: 'OA 2', text: 'Formular conjeturas y predicciones acerca de las causas o consecuencias de fenómenos naturales que observa, a partir de sus conocimientos y experiencias previas.' },
            { code: 'OA 3', text: 'Reconocer la importancia del agua y la energía solar para la vida humana, los animales y las plantas, a partir de experiencias directas o TICs.' },
            { code: 'OA 4', text: 'Comunicar propiedades básicas de los objetos y elementos naturales que explora, tales como: transparencia/opacidad, flexibilidad/rigidez, rugosidad/lisura, relacionándolos con posibles usos.' },
            { code: 'OA 5', text: 'Explorar los cambios o efectos que se producen en los materiales al aplicarles fuerza, calor o agua.' },
            { code: 'OA 6', text: 'Establecer relaciones de semejanzas y diferencias de animales y plantas, a partir de algunas características (tamaño, color, textura y morfología), sus necesidades básicas (formas de alimentación y abrigo), y los lugares que habitan, al observarlos en forma directa, en libros ilustrados o en TICs.' },
            { code: 'OA 7', text: 'Describir semejanzas y diferencias respecto a características, necesidades básicas y cambios que ocurren en el proceso de crecimiento, en personas, animales y plantas.' },
            { code: 'OA 8', text: 'Practicar algunas acciones cotidianas, que contribuyen al cuidado de ambientes sostenibles, tales como manejo de desechos en paseos al aire libre, separación de residuos, utilizar envases o papeles, plantar flores o árboles.' },
            { code: 'OA 9', text: 'Comunicar sus observaciones, los instrumentos utilizados y los hallazgos obtenidos en experiencias de indagación en el entorno natural, mediante relatos, representaciones gráficas o fotografías.' },
            { code: 'OA 10', text: 'Formular conjeturas a partir de los cambios observados en mezclas y disoluciones, estableciendo relaciones de posible causalidad y comunicándolas a través de diferentes medios.' },
            { code: 'OA 11', text: 'Identificar las condiciones que caracterizan los ambientes saludables, tales como: aire y agua limpia, combustión natural, reciclaje, reutilización y reducción de basura, tomando conciencia progresiva de cómo estas contribuyen a su salud.' },
            { code: 'OA 12', text: 'Comprender que la acción humana puede aportar al desarrollo de ambientes sostenibles y también al deterioro de estos.' },
          ],
        },
      },
      {
        id: 'comprension-entorno-sociocultural',
        name: 'Comprensión del entorno sociocultural',
        type: 'specific',
        oas: {
          salaCuna: [
            { code: 'OA 1', text: 'Imitar gestos y acciones que realizan personas de su entorno cercano.' },
            { code: 'OA 2', text: 'Identificar algunas actividades habituales que se realizan en su vida cotidiana, tales como: preparación de alimentos, rutinas antes de dormir, entre otras.' },
            { code: 'OA 3', text: 'Manifestar interés por canciones, juegos y bailes que forman parte de su cotidianeidad.' },
            { code: 'OA 4', text: 'Explorar utensilios domésticos y objetos tecnológicos que forman parte de su vida cotidiana, tales como: pocillos, envases de botellas, escobas, cucharas, teléfonos, entre otros, utilizándolos progresivamente en situaciones cotidianas y juegos.' },
            { code: 'OA 5', text: 'Reconocer objetos y personas, asociándolos a ciertos lugares, tales como: educadora/ técnico y jardín infantil; mamá/papá y casa; cama y dormir, recinto de cocina y comida, de su entorno sociocultural.' },
          ],
          nivelMedio: [
            { code: 'OA 1', text: 'Describir actividades habituales de su comunidad, como ir de compras, jugar en la plaza, viajar en bus, entre otras, señalando su participación en ellas.' },
            { code: 'OA 2', text: 'Describir características de las formas de vida de su comunidad (viviendas, paisajes, costumbres), a través de canciones, juegos, relatos y fotos familiares, entre otras.' },
            { code: 'OA 3', text: 'Seleccionar utensilios domésticos y objetos tecnológicos que les permiten resolver problemas en contextos sociales auténticos.' },
            { code: 'OA 4', text: 'Reconocer sucesos significativos de su historia personal y familiar, en diversas situaciones, tales como: conversaciones familiares, relatos de un agente comunitario, visitas a lugares, observación de fotografías, entre otros.' },
            { code: 'OA 5', text: 'Identificar instituciones significativas de su entorno, describiendo actividades y rutinas representativas que en ellas se realizan.' },
            { code: 'OA 6', text: 'Identificar algunas normas de protección y seguridad de su entorno cotidiano referidas a alimentación, tránsito y sismos, y otras pertinentes a su contexto geográfico.' },
            { code: 'OA 7', text: 'Distinguir en paisajes de su localidad, elementos naturales (bosque, cerros, ríos), y culturales (caminos, edificios, puentes).' },
          ],
          transicion: [
            { code: 'OA 1', text: 'Comprender los roles que desarrollan miembros de su familia y de su comunidad, y su aporte para el bienestar común.' },
            { code: 'OA 2', text: 'Apreciar diversas formas de vida de comunidades, del país y del mundo, en el pasado y en el presente, tales como: viviendas, paisajes, alimentación, costumbres, identificando mediante diversas fuentes de documentación gráfica y audiovisual, sus características relevantes.' },
            { code: 'OA 3', text: 'Comparar características de diseño, funcionamiento, utilidad, precaución de uso e impacto en el entorno, de diferentes objetos tecnológicos.' },
            { code: 'OA 4', text: 'Formular interpretaciones respecto de las necesidades y situaciones que dieron origen a creaciones e inventos, tales como: refrigerador, radio, avión, naves espaciales, cámara fotográfica, entre otros.' },
            { code: 'OA 5', text: 'Comunicar algunos relatos sociales sobre hechos significativos del pasado de su comunidad y país, apoyándose en recursos tales como: fotografías, videos, utensilios u objetos representativos.' },
            { code: 'OA 6', text: 'Reconocer diversas acciones para el cuidado del patrimonio cultural material (construcciones, obras de carácter arqueológico, lugares) e inmaterial (tradiciones, celebraciones), de su comunidad local.' },
            { code: 'OA 7', text: 'Reconocer la importancia del servicio que prestan instituciones, organizaciones, lugares y obras de interés patrimonial, tales como: escuelas, transporte público, empresas, iglesias, museos, bibliotecas, entre otros.' },
            { code: 'OA 8', text: 'Conocer sobre la vida de algunas mujeres y hombres, que han realizado en el pasado y en el presente, aportes diversos en su comunidad, país, y el mundo, a través de relatos, o con apoyo de TICs.' },
            { code: 'OA 9', text: 'Ampliar sus estrategias de indagación utilizando diversas fuentes, instrumentos y tecnologías de la información y comunicación, que le permitan expandir su entorno.' },
            { code: 'OA 10', text: 'Comprender normas de protección y seguridad referidas a tránsito, incendios, inundaciones, sismos, y otras pertinentes a su contexto geográfico.' },
            { code: 'OA 11', text: 'Identificar lugares de su entorno a través de su representación geográfica, tales como: maquetas, fotografías aéreas, dibujos y planos.' },
          ],
        },
      },
      {
        id: 'pensamiento-matematico',
        name: 'Pensamiento matemático',
        type: 'specific',
        oas: {
          salaCuna: [
            { code: 'OA 1', text: 'Adquirir la noción de permanencia de objetos y de personas significativas, mediante juegos con diversos objetos de uso cotidiano.' },
            { code: 'OA 2', text: 'Explorar a través de sus experiencias sensoriales y motrices, atributos de los objetos tales como: tamaño, textura y dureza.' },
            { code: 'OA 3', text: 'Experimentar con los objetos, resolviendo situaciones concretas, tales como: alcanzar objetos, apretar botones en aparatos sonoros, sacar juguetes de contenedores, juntar objetos, entre otros.' },
            { code: 'OA 4', text: 'Utilizar en situaciones lúdicas, nociones de ubicación en relación con su propio cuerpo tales como: dentro/fuera; encima/debajo.' },
            { code: 'OA 5', text: 'Orientarse temporalmente en situaciones cotidianas, siguiendo secuencias breves tales como: antes/después.' },
            { code: 'OA 6', text: 'Emplear cuantificadores (más/menos, mucho/poco), en situaciones cotidianas.' },
          ],
          nivelMedio: [
            { code: 'OA 1', text: 'Reproducir patrones sonoros, visuales, gestuales, corporales u otros, de dos o tres elementos.' },
            { code: 'OA 2', text: 'Experimentar con diversos objetos, estableciendo relaciones al clasificar por dos atributos a la vez (forma, color, entre otros) y seriar por altura o longitud.' },
            { code: 'OA 3', text: 'Describir la posición de objetos y personas, respecto de un punto u objeto de referencia, empleando conceptos de ubicación y distancia tales como: dentro/fuera; encima/debajo; cerca /lejos.' },
            { code: 'OA 4', text: 'Orientarse temporalmente en situaciones cotidianas, mediante la utilización progresiva de algunas nociones y relaciones de secuencias, tales como: antes/ después, día/noche, hoy/mañana.' },
            { code: 'OA 5', text: 'Emplear cuantificadores, tales como: más/menos, mucho/poco, todo/ninguno, al comparar cantidades de objetos en situaciones cotidianas.' },
            { code: 'OA 6', text: 'Emplear progresivamente los números, para contar, identificar, cuantificar y comparar cantidades, hasta el 10 e indicar orden o posición de algunos elementos en situaciones cotidianas o juegos.' },
            { code: 'OA 7', text: 'Representar progresivamente, números y cantidades en forma concreta y pictórica hasta el 10.' },
            { code: 'OA 8', text: 'Resolver progresivamente problemas simples, de manera concreta y pictórica, agregando o quitando hasta 5 elementos.' },
            { code: 'OA 9', text: 'Descubrir atributos de figuras 3D, mediante la exploración de objetos presentes en su entorno.' },
            { code: 'OA 10', text: 'Identificar algunas acciones que se llevaron a cabo para resolver problemas.' },
          ],
          transicion: [
            { code: 'OA 1', text: 'Crear patrones sonoros, visuales, gestuales, corporales u otros, de dos o tres elementos.' },
            { code: 'OA 2', text: 'Experimentar con diversos objetos estableciendo relaciones al clasificar por dos o tres atributos a la vez (forma, color, tamaño, función, masa, materialidad, entre otros) y seriar por altura, ancho, longitud o capacidad para contener.' },
            { code: 'OA 3', text: 'Comunicar la posición de objetos y personas respecto de un punto u objeto de referencia, empleando conceptos de ubicación (dentro/fuera; encima/debajo/entre; al frente de/detrás de); distancia (cerca/lejos) y dirección (adelante/atrás/hacia el lado), en situaciones lúdicas.' },
            { code: 'OA 4', text: 'Emplear cuantificadores, tales como: “más que”, “menos que”, “igual que”, al comparar cantidades de objetos en situaciones cotidianas.' },
            { code: 'OA 5', text: 'Orientarse temporalmente en situaciones cotidianas, empleando nociones y relaciones de secuencia (antes/ahora/después/al mismo tiempo, día/noche), frecuencia (siempre/a veces/ nunca) y duración (larga/corta).' },
            { code: 'OA 6', text: 'Emplear los números, para contar, identificar, cuantificar y comparar cantidades hasta el 20 e indicar orden o posición de algunos elementos en situaciones cotidianas o juegos.' },
            { code: 'OA 7', text: 'Representar números y cantidades hasta el 10, en forma concreta, pictórica y simbólica.' },
            { code: 'OA 8', text: 'Resolver problemas simples de manera concreta y pictórica agregando o quitando hasta 10 elementos, comunicando las acciones llevadas a cabo.' },
            { code: 'OA 9', text: 'Representar objetos desde arriba, del lado, abajo, a través de dibujos, fotografías o TICs, formulando conjeturas frente a sus descubrimientos.' },
            { code: 'OA 10', text: 'Identificar atributos de figuras 2D y 3D, tales como: forma, cantidad de lados, vértices, caras, que observa en forma directa o a través de TICs.' },
            { code: 'OA 11', text: 'Emplear medidas no estandarizadas, para determinar longitud de objetos, registrando datos, en diversas situaciones lúdicas o actividades cotidianas.' },
            { code: 'OA 12', text: 'Comunicar el proceso desarrollado en la resolución de problemas concretos, identificando la pregunta, acciones y posibles respuestas.' },
          ],
        },
      },
    ],
  },
];

export const ALL_NUCLEOS = AMBITOS.flatMap((a) => a.nucleos.map((n) => ({ ...n, ambito: a.name })));

export const getNucleoByName = (name) => ALL_NUCLEOS.find((n) => n.name === name) || null;

export const getOAsFor = ({ tramo, nucleoIds = null }) =>
  ALL_NUCLEOS.filter((n) => !nucleoIds || nucleoIds.includes(n.id)).flatMap((n) =>
    (n.oas[tramo] || []).map(({ code, text }) => ({
      ambito: n.ambito,
      nucleo: n.name,
      nucleoId: n.id,
      type: n.type,
      code,
      text,
    }))
  );
